# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 1.0
  - 1.3
  - nightly
matrix:
  allow_failures:
    - julia: nightly
  fast_finish: true
notifications:
  email: false
after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'

branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

jobs:
  allow_failures:
  - julia: nightly
  fast_finish: true
  include:
    - stage: "Examples"
      julia: 1.0
      os: linux
      script:
        - julia --project examples/examples.jl
    # - stage: "Documentation"
      # julia: 1.0
      # os: linux
      # script:
        # - julia --project=perf/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               # Pkg.instantiate()'
        # - julia --project=perf/ perf/samplers.jl
        # - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               # Pkg.instantiate()'
        # - julia --project=docs/ docs/make.jl
      # after_success: skip
